# Generated by Django 2.0 on 2019-07-12 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('removed', models.NullBooleanField()),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('date1', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
