# Generated by Django 2.0 on 2019-07-12 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='removed',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
    ]
