# Generated by Django 2.0 on 2019-07-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0002_auto_20190712_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='removed',
            field=models.NullBooleanField(),
        ),
    ]
