# Generated by Django 2.0 on 2019-07-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0003_article_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
