# Generated by Django 2.0 on 2019-07-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0004_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
