# Generated by Django 2.0 on 2019-07-12 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0005_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date1',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
