# Generated by Django 2.0 on 2019-07-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0006_article_date1'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
