# Generated by Django 2.0 on 2019-07-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0007_article_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
