# Generated by Django 2.0 on 2019-07-24 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0010_auto_20190724_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(db_column='author_age', default=0, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('telephone', models.CharField(max_length=11, unique=True)),
            ],
        ),
    ]
