# Generated by Django 2.0 on 2019-07-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0011_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='telephone',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
