# Generated by Django 2.0 on 2019-07-24 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0013_auto_20190724_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
