# Generated by Django 2.0 on 2019-07-24 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0014_auto_20190724_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
