# Generated by Django 2.0 on 2019-07-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0015_auto_20190724_1632'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
