
# Generated by Django 2.0 on 2019-08-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_temperature', models.BigIntegerField()),
                ('low_temperature', models.BigIntegerField()),
                ('weather_condition1', models.BigIntegerField()),
                ('weather_condition2', models.BigIntegerField()),
                ('wind_direction1', models.BigIntegerField()),
                ('wind_direction2', models.BigIntegerField()),
            ],
            options={
                'db_table': 'test_data1',
            },
        ),
    ]
