# Generated by Django 2.0 on 2019-09-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_testdata1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'img_address',
            },
        ),
    ]
