# Generated by Django 2.0 on 2019-09-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_imagedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'background_address',
            },
        ),
    ]
