# Generated by Django 2.0 on 2019-09-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_backgrounddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='YunFuWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.CharField(blank=True, max_length=20, null=True)),
                ('weather_condition1', models.CharField(blank=True, db_column='Weather_condition1', max_length=10, null=True)),
                ('weather_condition2', models.CharField(blank=True, db_column='Weather_condition2', max_length=10, null=True)),
                ('high_temperature', models.CharField(blank=True, max_length=10, null=True)),
                ('low_temperature', models.CharField(blank=True, max_length=10, null=True)),
                ('wind_direction1', models.CharField(blank=True, db_column='Wind_direction1', max_length=20, null=True)),
                ('wind_direction2', models.CharField(blank=True, db_column='Wind_direction2', max_length=20, null=True)),
            ],
            options={
                'db_table': 'yunfu_weather',
            },
        ),
    ]
